config/routes.rb
Rails.application.routes.draw do

	root "homes#home"
	get "/about", to:"homes#about"
	devise_for :users
	resources :posts, only:[:new, :create, :index, :show] do
		resource :post_comments, only: [:create, :destroy]
		resource :favorites, only: [:create, :destroy]
		resource :wannago_lists, only: [:create, :destroy]
	end

	devise_for :admins
	namespace :admins do
		root "homes#home"
		resources :categories, only:[:index, :create, :destroy]
	end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/browsing_history.rb
class BrowsingHistory < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :posts
end

app/models/chat.rb
class Chat < ApplicationRecord

	belongs_to :user
	belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :post_id, uniqueness: {scope: :user_id}
end

app/models/post.rb
class Post < ApplicationRecord

	acts_as_taggable
	
	has_many :post_images, dependent: :destroy
  	accepts_attachments_for :post_images, attachment: :image

	belongs_to :user
	belongs_to :category

	has_many :browsing_histories
	has_many :wannago_lists
	has_many :post_comments
	has_many :favorites
	
	def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
  	end

  	def wannago_listed_by?(user)
    	wannago_lists.where(user_id: user.id).exists?
  	end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :post
  	attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord

	has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :favorites
  has_many :wannago_lists
  has_many :chats
  has_many :browsing_histories
  has_many :post_comments
  has_many :user_rooms
  
  attachment :image, destroy: false
end

app/models/user_room.rb
class UserRoom < ApplicationRecord

	belongs_to :user
	belongs_to :room
end

app/models/wannago_list.rb
class WannagoList < ApplicationRecord

	belongs_to :user
	belongs_to :post

	validates :post_id, uniqueness: {scope: :user_id}
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		@post = Post.new
		@categories = Category.all
		@post.post_images.build
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		@post.save
		redirect_to new_post_path
	end

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
		@post_comment = PostComment.new
	end

	
	private
	def post_params
		params.require(:post).permit(:user_id, :title, :category_id, :image, :content, :place, :tips, :course, :tag_list, post_images_images: [])
	end
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_comment_form.html.erb
<%= form_with model: [post, post_comment] do |f| %>
    <%= f.text_area :comment, class: "form-control" %>
    <%= f.submit '送信' %>
<% end %>

app/views/posts/_comments.html.erb
<p><%= post.post_comments.count %>件のコメント</p>
<table class="table">
	<% post.post_comments.each do |post_comment| %>
	<tr>
		<td width="50">
			<%= attachment_image_tag(post_comment.user, :image, :fill, 40, 40, class: "rounded-circle float-left img", fallback: "no-image-mini.jpg") %>
		</td>
		<td width="30">
			<%= post_comment.user.name %>
		</td>
		<td>
			<p><%= post_comment.comment %></p>
		</td>
		<td width="127">
			<%= post_comment.created_at.strftime('%Y/%m/%d') %>
			<% if current_user == post_comment.user %>
				<%= link_to '', post_post_comments_path(post_comment), method: :delete, class: "far fa-trash-alt", remote: true %>
			<% end %>
		</td>
	</tr>
	<% end %>
</table>

app/views/posts/_favorite.html.erb
<% if post.favorited_by?(current_user) %>
	<%= link_to post_favorites_path(post), method: :delete, remote: true do %> 
		<i class="fas fa-heart"><%= post.favorites.count %></i>
	<% end %> 
<% else %>
	<%= link_to post_favorites_path(post), method: :post, remote: true do %> 
		<i class="far fa-heart"><%= post.favorites.count %></i> 
	<% end %> 
<% end %>

app/views/posts/_wannago.html.erb
<%= post.title %>
<% if post.wannago_listed_by?(current_user) %>
	<%= link_to post_wannago_lists_path(post), method: :delete, remote: true do %> 
		<i class="fas fa-calendar-check"><%= post.wannago_lists.count %></i>
	<% end %>
<% else %>
	<%= link_to post_wannago_lists_path(post), method: :post, remote: true do %> 
		<i class="far fa-calendar-check"><%= post.wannago_lists.count %></i>
	<% end %>
<% end %>

app/views/posts/index.html.erb
<table class="table">
	<% @posts.each do |post| %>
		<tr>
			<td>
				<%= link_to post.title, post_path(post.id), data: {"turbolinks" => false} %>
			</td>
			<td>
				<% post.tags.each do |tag| %>
				     <%= tag.name %>
				<% end %>
			</td>
		</tr>

	<% end %>
</table>

app/views/posts/new.html.erb
<div class="container-fluid">
 	<div class="row">
 		<div class="col-2 offset-5">
 			<h1 class="text-center">旅を書く</h1>
 		</div>
 	</div>
</div>

<%= form_for(@post) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title, autofocus: true  %>

	<%= f.label :place, :場所名 %>
	<%= f.text_field :place, autofocus: true  %>

	<%= f.attachment_field :post_images_images, multiple: true %>

	<%= f.label :category_id, :カテゴリー %>
	<%= f.collection_select :category_id, @categories, :id, :name, include_blank: "選択してください" %>

	<%= f.label :content, :コメント %>
	<%= f.text_area :content, autofocus: true  %>

	<%= f.label :tips, :ちょっとした情報（お得情報や注意した方がよいことなど） %>
	<%= f.text_area :tips, autofocus: true  %>

	<%= f.label :course, :おすすめコース %>
	<%= f.text_area :course, autofocus: true  %>

	<%= f.label :tag_list, :スペースで区切ってタグを入力 %>
	<%= f.text_field :tag_list, value: @post.tag_list.join(',') %>

	<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-10 offset-1">
			<div class="row">
				<div class="col-lg-8">
					<div class="row">
						<div class="col-lg-12">
							<div class="clearfix">
								<div class="wannago">
									<%= render "wannago", post: @post %>
								</div>
								<div class="favorite">
									<%= render "favorite", post: @post %>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<div class="bxslider2">
								<% @post.post_images.each do |image|%>
									<%= attachment_image_tag image, :image,fallback: "no_image.jpg", class: "postimg" %>
								<% end %>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<%= @post.content %>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<%= @post.tips %>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<%= @post.course%>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-5">
							<div>
								<% @post.tags.each do |tag| %>
									<%= tag.name %>
								<% end %>
							</div>
							<div>投稿者：<%= @post.user.name %>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<div class="comments">
								<%= render "comments", post: @post %>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<div class="comment-form">
								<%= render "comment_form", post: @post, post_comment: @post_comment %>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="row">
						<div class="col-lg-12">
							グーグルマップ
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							直前の閲覧履歴
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>