config/routes.rb
Rails.application.routes.draw do

	root "homes#home"
	get "/about", to:"homes#about"
	devise_for :users
	resources :posts, only:[:new, :create, :index, :show] do
		resource :post_comments, only: [:create, :destroy]
		resource :favorites, only: [:create, :destroy]
		resource :wannago_lists, only: [:create, :destroy]
	end

	devise_for :admins
	namespace :admins do
		root "homes#home"
		resources :categories, only:[:index, :create, :destroy]
	end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/browsing_history.rb
class BrowsingHistory < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :posts
end

app/models/chat.rb
class Chat < ApplicationRecord

	belongs_to :user
	belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :post_id, uniqueness: {scope: :user_id}
end

app/models/post.rb
class Post < ApplicationRecord

	acts_as_taggable
	
	has_many :post_images, dependent: :destroy
  	accepts_attachments_for :post_images, attachment: :image

	belongs_to :user
	belongs_to :category

	has_many :browsing_histories
	has_many :wannago_lists
	has_many :post_comments
	has_many :favorites
	
	def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
  	end

  	def wannago_listed_by?(user)
    	wannago_lists.where(user_id: user.id).exists?
  	end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :post
  	attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord

	has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :favorites
  has_many :wannago_lists
  has_many :chats
  has_many :browsing_histories
  has_many :post_comments
  has_many :user_rooms
  
  attachment :image, destroy: false
end

app/models/user_room.rb
class UserRoom < ApplicationRecord

	belongs_to :user
	belongs_to :room
end

app/models/wannago_list.rb
class WannagoList < ApplicationRecord

	belongs_to :user
	belongs_to :post

	validates :post_id, uniqueness: {scope: :user_id}
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_admin_header.html.erb
<div class="container">
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <%= link_to admins_root_path, class: "navbar-brand", data: {"turbolinks" => false} do%>
        <%= image_tag "logo.png", :size => '150x100' %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to "会員一覧", "#", class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
          <li class="nav-item">
            <%= link_to "旅投稿一覧", "#", class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
          <li class="nav-item">
            <%= link_to "カテゴリー一覧", admins_categories_path, class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </header>
</div>

app/views/layouts/_customer_header.html.erb
<div class="container">
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <%= link_to root_path, class: "navbar-brand", data: {"turbolinks" => false} do%>
        <%= image_tag "logo.png", :size => '150x100' %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to "マイページ", "#", class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
          <li class="nav-item">
            <%= link_to "お気に入り", "#", class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
          <li class="nav-item">
            <%= link_to "タイムライン", "#", class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
          <li class="nav-item">
            <%= link_to "旅をかく", new_post_path, class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </header>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container-fluid">
		<p style="text-align: right; font-size: 12px; color: #777777; margin-top: 12px; margin-bottom: 0;" >旅好き。｜　旅情報共有SNS。「見つかる。あなた史上の旅。」TabiZuki © 2020
		</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <%= link_to root_path, class: "navbar-brand", data: {"turbolinks" => false} do%>
        <%= image_tag "logo.png", :size => '150x100' %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, 
            class: "nav-link", data: {"turbolinks" => false} %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, 
            class: "nav-link", data: {"turbolinks" => false} %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnEnglish</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/ce5151405c.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render "layouts/customer_header" %>
    <% elsif admin_signed_in? %>
      <%= render "layouts/admin_header" %>
    <% else %>
      <%= render "layouts/header" %>
    <% end %>

    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
</html>